#!/bin/bash

set -a

if ! echo "${1}" | egrep '(pass|note|fin)'; then
  echo "Supported notebook types are [pass/note/fin]"
fi

SCRIPT_DIR="$(dirname $(readlink -f $0))"
cd "${SCRIPT_DIR}"
DATE_STRING="`date +%Y%m%d%H%M%S`"
FILENAME="${1}"
ENC_FILE="${SCRIPT_DIR}/../${FILENAME}.enc"
TMP_DIR="/dev/shm"
ENC_FILE_IN_TAR_NAME="${DATE_STRING}_${FILENAME}.enc"
ENC_FILE_IN_TAR_PATH="${TMP_DIR}/${ENC_FILE_IN_TAR_NAME}"
ARCHIVE_PATH="${SCRIPT_DIR}/../archive.tar"
TMP_FILE="${TMP_DIR}/notebook.plain"
rm -f "${TMP_FILE}"
trap 'dd >/dev/null 2>&1 if=/dev/urandom of="${TMP_FILE}" bs=1k count=100; rm -f "${TMP_FILE}"' EXIT
echo -n Password: 
read -s PASSWORD 
echo
if [ "xEDIT" == "x$2" ]; then
  openssl aes-256-cbc -md md5 -pass env:PASSWORD -a -salt -d -in "${ENC_FILE}" >"${TMP_FILE}" || exit
  nvim "${TMP_FILE}"
  openssl aes-256-cbc -md md5 -pass env:PASSWORD -a -salt -in "${TMP_FILE}" > "${ENC_FILE_IN_TAR_PATH}"
  tar rvf "${ARCHIVE_PATH}" -C "${TMP_DIR}" "${ENC_FILE_IN_TAR_NAME}"
  mv "${ENC_FILE_IN_TAR_PATH}" "${ENC_FILE}"

else
  openssl aes-256-cbc -md md5 -pass env:PASSWORD -a -salt -d -in "${ENC_FILE}" | less
fi

